In [1]:
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.pipeline import make_pipeline
import pickle

In [2]:
#AdaBoost meta estimator
from sklearn.ensemble import AdaBoostClassifier

#Base Model, chosen decision tree
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [4]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import pickle

# Load dataset
features = np.load('features.npy')
labels = np.load('target.npy')

# Check the shapes of the arrays
print(f'Features shape: {features.shape}')
print(f'Labels shape: {labels.shape}')

# Ensure the number of samples matches
if features.shape[0] != labels.shape[0]:
    raise ValueError(f'Mismatched number of samples: {features.shape[0]} in features, {labels.shape[0]} in labels')

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

# Initialize the base model
base_model = DecisionTreeClassifier(max_depth=1)

# Initialize the AdaBoost classifier with the base model
ada_model = AdaBoostClassifier(estimator=base_model, n_estimators=50, random_state=42)

# Train the model
ada_model.fit(X_train, y_train)

# Make predictions
y_pred = ada_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

# Print classification report
print('Classification Report:')
print(classification_report(y_test, y_pred))

# Print confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Save the trained model using pickle
with open('ada_model.pkl', 'wb') as f:
    pickle.dump(ada_model, f)


Features shape: (2847, 4096)
Labels shape: (2847,)


c:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Accuracy: 0.3351
Classification Report:
              precision    recall  f1-score   support

           0       0.27      0.19      0.22        86
           1       0.15      0.06      0.09        66
           2       0.75      0.59      0.66        73
           3       0.21      0.65      0.32        84
           4       0.78      0.71      0.74        59
           5       0.07      0.03      0.04        61
           6       0.17      0.07      0.10        67
           7       0.45      0.32      0.38        74

    accuracy                           0.34       570
   macro avg       0.36      0.33      0.32       570
weighted avg       0.35      0.34      0.32       570

Confusion Matrix:
[[16  4  4 46  2  7  3  4]
 [13  4  3 36  2  2  2  4]
 [ 2  6 43  2  5 11  4  0]
 [ 8  3  3 55  1  2  5  7]
 [ 7  3  0  1 42  3  1  2]
 [ 4  1  3 37  2  2  6  6]
 [ 4  3  0 47  0  2  5  6]
 [ 6  3  1 36  0  1  3 24]]


In [7]:
# Initialize the AdaBoost classifier with increased number of estimators and tuned learning rate
ada_model = AdaBoostClassifier(n_estimators=1000, learning_rate=1, random_state=42)

# Train the model
ada_model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = ada_model.predict(X_test)
y_train_pred = ada_model.predict(X_train)

# Evaluate the model
test_accuracy = accuracy_score(y_test, y_pred)
print(f'Testing Accuracy: {accuracy:.4f}')
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f'Training Accuracy: {accuracy:.4f}')

# Print classification report
print('Classification Report:')
print(classification_report(y_test, y_pred))

# Print confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Save the trained model using pickle
with open('ada_model.pkl', 'wb') as f:
    pickle.dump(ada_model, f)

c:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Testing Accuracy: 0.3351
Training Accuracy: 0.3351
Classification Report:
              precision    recall  f1-score   support

           0       0.37      0.38      0.38        86
           1       0.27      0.18      0.22        66
           2       0.76      0.73      0.74        73
           3       0.28      0.15      0.20        84
           4       0.84      0.78      0.81        59
           5       0.22      0.59      0.32        61
           6       0.31      0.18      0.23        67
           7       0.41      0.34      0.37        74

    accuracy                           0.40       570
   macro avg       0.43      0.42      0.41       570
weighted avg       0.42      0.40      0.40       570

Confusion Matrix:
[[33  2  5  9  1 28  3  5]
 [14 12  3  8  0 15  7  7]
 [ 2  0 53  3  8  3  3  1]
 [14 10  3 13  0 34  3  7]
 [ 5  1  0  1 46  3  0  3]
 [ 4  0  5  3  0 36  7  6]
 [ 9 11  0  4  0 24 12  7]
 [ 8  8  1  6  0 22  4 25]]
